name: Set Postfix Value
description: Set the POSTFIX value for according the received channel and pre-release values.

inputs:
  CHANNEL:
    required: true
    description: 'The channel to get the version to (ga, cloud, beta).'
  PRERELEASE:
    required: false
    description: 'Is this a pre-release?'

runs:
  using: "composite"
  steps:
    - name: Set POSTFIX value
      id: set-postfix-value
      shell: bash
      run: |
        # Set the postfix value

        POSTFIX=""
        if [[ ${{ inputs.PRERELEASE }} == 'true' ]]; then
          POSTFIX="-test"
        fi

        #echo "set-output name=POSTFIX::${POSTFIX}"
        echo "POSTFIX=${POSTFIX}" >> $GITHUB_OUTPUT
